/*
 * generated by Xtext 2.17.1
 */
package de.fraunhofer.isst.stars.ui.tests;

import com.google.inject.Injector;
import de.fraunhofer.isst.automotive.stars.reqmon.dsl.requirement.ui.internal.RequirementActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RequirementDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RequirementActivator.getInstance().getInjector("de.fraunhofer.isst.stars.RequirementDSL");
	}

}
