/*
* Generated by STARS Dadas.
* All Rights reserved by Fraunhofer-Institut Software- und Systemtechnik ISST.
* 
* Generated by stars
* Project: test
* 
*/

#ifndef __TYPES_HEADER_
#define __TYPES_HEADER_

#define MEDIATYPE_DADAS (MEDIA_TYPE_USER + 0xC350)
#define MEDIASUBTYPE_SCENE 0x0010
#define MEDIASUBTYPE_TIME 0x0020
#define MEDIASUBTYPE_CATEGORIZATION 0x0030
#define MEDIASUBTYPE_ABSTRACT_TARGETS 0x0040
#define MEDIASUBTYPE_CONCRETE_TARGETS 0x0050
#define MEDIASUBTYPE_CAN 0x0060

#endif //__TYPES_HEADER_
