/**
 * generated by Xtext 2.14.0
 */
package de.fraunhofer.isst.stars;

import de.fraunhofer.isst.stars.AbstractRequirementDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RequirementDSLRuntimeModule extends AbstractRequirementDSLRuntimeModule {
}
