/**
 * generated by Xtext 2.17.1
 */
package de.fraunhofer.isst.stars.requirementDSL.impl;

import de.fraunhofer.isst.stars.requirementDSL.RelObjects;
import de.fraunhofer.isst.stars.requirementDSL.Relation;
import de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.impl.RelationImpl#getRelposAdv <em>Relpos Adv</em>}</li>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.impl.RelationImpl#getRelDel <em>Rel Del</em>}</li>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.impl.RelationImpl#getRelComp <em>Rel Comp</em>}</li>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.impl.RelationImpl#getRelElements <em>Rel Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelationImpl extends MinimalEObjectImpl.Container implements Relation
{
  /**
   * The default value of the '{@link #getRelposAdv() <em>Relpos Adv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelposAdv()
   * @generated
   * @ordered
   */
  protected static final String RELPOS_ADV_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRelposAdv() <em>Relpos Adv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelposAdv()
   * @generated
   * @ordered
   */
  protected String relposAdv = RELPOS_ADV_EDEFAULT;

  /**
   * The default value of the '{@link #getRelDel() <em>Rel Del</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelDel()
   * @generated
   * @ordered
   */
  protected static final String REL_DEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRelDel() <em>Rel Del</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelDel()
   * @generated
   * @ordered
   */
  protected String relDel = REL_DEL_EDEFAULT;

  /**
   * The default value of the '{@link #getRelComp() <em>Rel Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelComp()
   * @generated
   * @ordered
   */
  protected static final String REL_COMP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRelComp() <em>Rel Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelComp()
   * @generated
   * @ordered
   */
  protected String relComp = REL_COMP_EDEFAULT;

  /**
   * The cached value of the '{@link #getRelElements() <em>Rel Elements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelElements()
   * @generated
   * @ordered
   */
  protected RelObjects relElements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RequirementDSLPackage.Literals.RELATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRelposAdv()
  {
    return relposAdv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelposAdv(String newRelposAdv)
  {
    String oldRelposAdv = relposAdv;
    relposAdv = newRelposAdv;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RequirementDSLPackage.RELATION__RELPOS_ADV, oldRelposAdv, relposAdv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRelDel()
  {
    return relDel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelDel(String newRelDel)
  {
    String oldRelDel = relDel;
    relDel = newRelDel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RequirementDSLPackage.RELATION__REL_DEL, oldRelDel, relDel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRelComp()
  {
    return relComp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelComp(String newRelComp)
  {
    String oldRelComp = relComp;
    relComp = newRelComp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RequirementDSLPackage.RELATION__REL_COMP, oldRelComp, relComp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelObjects getRelElements()
  {
    return relElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRelElements(RelObjects newRelElements, NotificationChain msgs)
  {
    RelObjects oldRelElements = relElements;
    relElements = newRelElements;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RequirementDSLPackage.RELATION__REL_ELEMENTS, oldRelElements, newRelElements);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelElements(RelObjects newRelElements)
  {
    if (newRelElements != relElements)
    {
      NotificationChain msgs = null;
      if (relElements != null)
        msgs = ((InternalEObject)relElements).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RequirementDSLPackage.RELATION__REL_ELEMENTS, null, msgs);
      if (newRelElements != null)
        msgs = ((InternalEObject)newRelElements).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RequirementDSLPackage.RELATION__REL_ELEMENTS, null, msgs);
      msgs = basicSetRelElements(newRelElements, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RequirementDSLPackage.RELATION__REL_ELEMENTS, newRelElements, newRelElements));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.RELATION__REL_ELEMENTS:
        return basicSetRelElements(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.RELATION__RELPOS_ADV:
        return getRelposAdv();
      case RequirementDSLPackage.RELATION__REL_DEL:
        return getRelDel();
      case RequirementDSLPackage.RELATION__REL_COMP:
        return getRelComp();
      case RequirementDSLPackage.RELATION__REL_ELEMENTS:
        return getRelElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.RELATION__RELPOS_ADV:
        setRelposAdv((String)newValue);
        return;
      case RequirementDSLPackage.RELATION__REL_DEL:
        setRelDel((String)newValue);
        return;
      case RequirementDSLPackage.RELATION__REL_COMP:
        setRelComp((String)newValue);
        return;
      case RequirementDSLPackage.RELATION__REL_ELEMENTS:
        setRelElements((RelObjects)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.RELATION__RELPOS_ADV:
        setRelposAdv(RELPOS_ADV_EDEFAULT);
        return;
      case RequirementDSLPackage.RELATION__REL_DEL:
        setRelDel(REL_DEL_EDEFAULT);
        return;
      case RequirementDSLPackage.RELATION__REL_COMP:
        setRelComp(REL_COMP_EDEFAULT);
        return;
      case RequirementDSLPackage.RELATION__REL_ELEMENTS:
        setRelElements((RelObjects)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.RELATION__RELPOS_ADV:
        return RELPOS_ADV_EDEFAULT == null ? relposAdv != null : !RELPOS_ADV_EDEFAULT.equals(relposAdv);
      case RequirementDSLPackage.RELATION__REL_DEL:
        return REL_DEL_EDEFAULT == null ? relDel != null : !REL_DEL_EDEFAULT.equals(relDel);
      case RequirementDSLPackage.RELATION__REL_COMP:
        return REL_COMP_EDEFAULT == null ? relComp != null : !REL_COMP_EDEFAULT.equals(relComp);
      case RequirementDSLPackage.RELATION__REL_ELEMENTS:
        return relElements != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (relposAdv: ");
    result.append(relposAdv);
    result.append(", relDel: ");
    result.append(relDel);
    result.append(", relComp: ");
    result.append(relComp);
    result.append(')');
    return result.toString();
  }

} //RelationImpl
