/**
 * generated by Xtext 2.17.1
 */
package de.fraunhofer.isst.stars.requirementDSL.impl;

import de.fraunhofer.isst.stars.requirementDSL.Property;
import de.fraunhofer.isst.stars.requirementDSL.RelObjects;
import de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rel Objects</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.impl.RelObjectsImpl#getObject <em>Object</em>}</li>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.impl.RelObjectsImpl#getProperty <em>Property</em>}</li>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.impl.RelObjectsImpl#getRelConj <em>Rel Conj</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelObjectsImpl extends MinimalEObjectImpl.Container implements RelObjects
{
  /**
   * The cached value of the '{@link #getObject() <em>Object</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObject()
   * @generated
   * @ordered
   */
  protected EList<de.fraunhofer.isst.stars.requirementDSL.Object> object;

  /**
   * The cached value of the '{@link #getProperty() <em>Property</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperty()
   * @generated
   * @ordered
   */
  protected EList<Property> property;

  /**
   * The cached value of the '{@link #getRelConj() <em>Rel Conj</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelConj()
   * @generated
   * @ordered
   */
  protected EList<String> relConj;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelObjectsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RequirementDSLPackage.Literals.REL_OBJECTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<de.fraunhofer.isst.stars.requirementDSL.Object> getObject()
  {
    if (object == null)
    {
      object = new EObjectContainmentEList<de.fraunhofer.isst.stars.requirementDSL.Object>(de.fraunhofer.isst.stars.requirementDSL.Object.class, this, RequirementDSLPackage.REL_OBJECTS__OBJECT);
    }
    return object;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Property> getProperty()
  {
    if (property == null)
    {
      property = new EObjectContainmentEList<Property>(Property.class, this, RequirementDSLPackage.REL_OBJECTS__PROPERTY);
    }
    return property;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getRelConj()
  {
    if (relConj == null)
    {
      relConj = new EDataTypeEList<String>(String.class, this, RequirementDSLPackage.REL_OBJECTS__REL_CONJ);
    }
    return relConj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.REL_OBJECTS__OBJECT:
        return ((InternalEList<?>)getObject()).basicRemove(otherEnd, msgs);
      case RequirementDSLPackage.REL_OBJECTS__PROPERTY:
        return ((InternalEList<?>)getProperty()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.REL_OBJECTS__OBJECT:
        return getObject();
      case RequirementDSLPackage.REL_OBJECTS__PROPERTY:
        return getProperty();
      case RequirementDSLPackage.REL_OBJECTS__REL_CONJ:
        return getRelConj();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.REL_OBJECTS__OBJECT:
        getObject().clear();
        getObject().addAll((Collection<? extends de.fraunhofer.isst.stars.requirementDSL.Object>)newValue);
        return;
      case RequirementDSLPackage.REL_OBJECTS__PROPERTY:
        getProperty().clear();
        getProperty().addAll((Collection<? extends Property>)newValue);
        return;
      case RequirementDSLPackage.REL_OBJECTS__REL_CONJ:
        getRelConj().clear();
        getRelConj().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.REL_OBJECTS__OBJECT:
        getObject().clear();
        return;
      case RequirementDSLPackage.REL_OBJECTS__PROPERTY:
        getProperty().clear();
        return;
      case RequirementDSLPackage.REL_OBJECTS__REL_CONJ:
        getRelConj().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RequirementDSLPackage.REL_OBJECTS__OBJECT:
        return object != null && !object.isEmpty();
      case RequirementDSLPackage.REL_OBJECTS__PROPERTY:
        return property != null && !property.isEmpty();
      case RequirementDSLPackage.REL_OBJECTS__REL_CONJ:
        return relConj != null && !relConj.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (relConj: ");
    result.append(relConj);
    result.append(')');
    return result.toString();
  }

} //RelObjectsImpl
