/**
 * generated by Xtext 2.14.0
 */
package de.fraunhofer.isst.stars.requirementDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getClause()
 * @model
 * @generated
 */
public interface Clause extends EObject
{
} // Clause
