/**
 * generated by Xtext 2.14.0
 */
package de.fraunhofer.isst.stars.requirementDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraints</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.Constraints#getTimeConstraint <em>Time Constraint</em>}</li>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.Constraints#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getConstraints()
 * @model
 * @generated
 */
public interface Constraints extends EObject
{
  /**
   * Returns the value of the '<em><b>Time Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time Constraint</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Constraint</em>' containment reference.
   * @see #setTimeConstraint(TimeConstraint)
   * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getConstraints_TimeConstraint()
   * @model containment="true"
   * @generated
   */
  TimeConstraint getTimeConstraint();

  /**
   * Sets the value of the '{@link de.fraunhofer.isst.stars.requirementDSL.Constraints#getTimeConstraint <em>Time Constraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Constraint</em>' containment reference.
   * @see #getTimeConstraint()
   * @generated
   */
  void setTimeConstraint(TimeConstraint value);

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference.
   * @see #setConstraint(Constraint)
   * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getConstraints_Constraint()
   * @model containment="true"
   * @generated
   */
  Constraint getConstraint();

  /**
   * Sets the value of the '{@link de.fraunhofer.isst.stars.requirementDSL.Constraints#getConstraint <em>Constraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint</em>' containment reference.
   * @see #getConstraint()
   * @generated
   */
  void setConstraint(Constraint value);

} // Constraints
