/**
 * generated by Xtext 2.14.0
 */
package de.fraunhofer.isst.stars.requirementDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.ObjectConstraint#getObject <em>Object</em>}</li>
 * </ul>
 *
 * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getObjectConstraint()
 * @model
 * @generated
 */
public interface ObjectConstraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' containment reference.
   * @see #setObject(de.fraunhofer.isst.stars.requirementDSL.Object)
   * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getObjectConstraint_Object()
   * @model containment="true"
   * @generated
   */
  de.fraunhofer.isst.stars.requirementDSL.Object getObject();

  /**
   * Sets the value of the '{@link de.fraunhofer.isst.stars.requirementDSL.ObjectConstraint#getObject <em>Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' containment reference.
   * @see #getObject()
   * @generated
   */
  void setObject(de.fraunhofer.isst.stars.requirementDSL.Object value);

} // ObjectConstraint
