/**
 * generated by Xtext 2.17.1
 */
package de.fraunhofer.isst.stars.requirementDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.RequirementText#getCondClauses <em>Cond Clauses</em>}</li>
 *   <li>{@link de.fraunhofer.isst.stars.requirementDSL.RequirementText#getMainclauses <em>Mainclauses</em>}</li>
 * </ul>
 *
 * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getRequirementText()
 * @model
 * @generated
 */
public interface RequirementText extends EObject
{
  /**
   * Returns the value of the '<em><b>Cond Clauses</b></em>' containment reference list.
   * The list contents are of type {@link de.fraunhofer.isst.stars.requirementDSL.ConditionalClause}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond Clauses</em>' containment reference list.
   * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getRequirementText_CondClauses()
   * @model containment="true"
   * @generated
   */
  EList<ConditionalClause> getCondClauses();

  /**
   * Returns the value of the '<em><b>Mainclauses</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mainclauses</em>' containment reference.
   * @see #setMainclauses(MainClause)
   * @see de.fraunhofer.isst.stars.requirementDSL.RequirementDSLPackage#getRequirementText_Mainclauses()
   * @model containment="true"
   * @generated
   */
  MainClause getMainclauses();

  /**
   * Sets the value of the '{@link de.fraunhofer.isst.stars.requirementDSL.RequirementText#getMainclauses <em>Mainclauses</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mainclauses</em>' containment reference.
   * @see #getMainclauses()
   * @generated
   */
  void setMainclauses(MainClause value);

} // RequirementText
