#ifndef __TYPES_HEADER_
#define __TYPES_HEADER_

#define MEDIATYPE_PATH_PLANING (MEDIA_TYPE_USER + 0x5555)
#define MEDIASUBTYPE_SCENE 0x0010
#define MEDIASUBTYPE_SCENE_PREDICTED 0x0012
#define MEDIASUBTYPE_TARGETPOINT      0x0030
#define MEDIASUBTYPE_TARGETPOINT_MESSAGE 0x0031
#define MEDIASUBTYPE_TARGETPOINT_MESSAGE_PREDICTED 0x0032

#include <driving/types/dataTypes.h>

#endif //__TYPES_HEADER_